name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.13']
        os: [ubuntu-latest]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      env:
        WSK_INSTALL: https://github.com/apache/openwhisk-cli/releases/download/1.0.0/OpenWhisk_CLI-1.0.0-linux-amd64.tgz
        NVM_INSTALL: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
        JQ_INSTALL: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      run: |
        curl -sL $WSK_INSTALL | sudo tar xzvf - -C /usr/bin wsk
        curl -o- "$NVM_INSTALL" | bash
        sudo curl -sL $JQ_INSTALL -o /usr/bin/jq && sudo chmod +x /usr/bin/jq
        source $HOME/.nvm/nvm.sh
        nvm install v10
        sudo apt-get -y install python3.7
        sudo ln -sf /usr/bin/python3.7 /usr/bin/python3
        git clone https://github.com/sstephenson/bats.git
        cd bats
        sudo ./install.sh /usr/local

    - name: NgrokPre
      run: if grep pre .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: WaitPre
      run: if grep pre .github/ngrok ; then bash .github/wait.sh ; fi
   
    - name: Build
      shell: bash
      env: 
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        source $HOME/.nvm/nvm.sh
        nvm use v10
        docker login -u iosdk -p "$DOCKER_TOKEN"
        make

    - name: NgrokPost
      run: if grep post .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: WaitPost
      run: if grep post .github/ngrok ; then bash .github/wait.sh ; fi
