name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: NgrokPre
      run: if grep pre .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: WaitPre
      run: if grep pre .github/ngrok ; then bash .github/wait.sh ; fi
   
    - name: Build
      shell: bash
      env: 
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        docker login -u iosdk -p "$DOCKER_TOKEN"
        source setup.sh
        make

    - name: NgrokPost
      run: if grep post .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: WaitPost
      run: if grep post .github/ngrok ; then bash .github/wait.sh ; fi
