name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.13']
        os: [ubuntu-latest]
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      env:
        WSK_INSTALL: https://github.com/apache/openwhisk-cli/releases/download/1.0.0/OpenWhisk_CLI-1.0.0-linux-amd64.tgz
        NVM_INSTALL: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
        JQ_INSTALL: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      run: |
        curl -sL $WSK_INSTALL | sudo tar xzvf - -C /usr/bin wsk
        curl -o- "$NVM_INSTALL" | bash
        curl -sL $JQ_INSTALL | sudo tee /usr/bin/jq && sudo chmod +x /usr/bin/jq
        source $HOME/.nvm/nvm.sh
        nvm install v10
        sudo apt-get -y install httpie
        git clone https://github.com/sstephenson/bats.git
        cd bats
        sudo ./install.sh /usr/local

    - name: Build
      shell: bash
      env: 
        DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        source $HOME/.nvm/nvm.sh
        nvm use v10
        docker login -u iosdk -p "$DOCKER_HUB_ACCESS_TOKEN"
        make

    # uncomment this if you need to debug...
    #- name: Ngrok
    #  run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
    #  env:
    #    NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    #    USER_PASS: ${{ secrets.USER_PASS }}
    #- name: Sleep
    #  run: sleep 1h
   
